name: sirpy
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - gdal
  - pytest
  - pip:
      - "--editable=git+https://github.com/tmilliman/sirpy2.git#egg=sirpy2-master"
